<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Yashu.local" name="Default test" tests="22" failures="1" timestamp="22 Apr 2016 04:18:35 GMT" time="0.415" errors="0">
  <testcase name="compilingCode_throwsUndeclaredVariableException_ifReadingUndefinedVariable" time="0.099" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="compilingCode_throwsUndeclaredVariableException_ifWritingUndefinedVariable" time="0.009" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="compilingCode_throwsVariableAlreadyDefinedException_whenDefiningAlreadyDefinedVariable" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.017" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.009" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.009" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.006" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.004" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.004" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.011" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.012" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.005" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.003" classname="edu.asu.compiler.test.CompilerTest"/>
  <testcase name="runningCode_outputsExpectedText" time="0.01" classname="edu.asu.compiler.test.CompilerTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at edu.asu.compiler.test.CompilerTest.runningCode_outputsExpectedText(CompilerTest.java:67)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- runningCode_outputsExpectedText -->
</testsuite> <!-- Default test -->
